// lib/db/src/seed.ts
// Seed script — populates Neon database with all 56 AIPS products + 8 categories
// Run: pnpm --filter @workspace/db db:seed

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { productsTable, categoriesTable } from "./schema/index.js";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const categories = [
  { id: "ai-assistant",   name: "AI Assistants",    description: "ChatGPT, Claude, Gemini, Grok, Perplexity and more", icon: "🤖", sortOrder: 1 },
  { id: "ai-image",       name: "AI Image",          description: "Midjourney, Ideogram, Leonardo AI", icon: "🎨", sortOrder: 2 },
  { id: "ai-video",       name: "AI Video",          description: "Runway, HeyGen", icon: "🎬", sortOrder: 3 },
  { id: "ai-voice-music", name: "AI Voice & Music",  description: "ElevenLabs, Suno, Udio", icon: "🎵", sortOrder: 4 },
  { id: "ai-code",        name: "AI Code & Dev",     description: "GitHub Copilot, Cursor, Replit", icon: "💻", sortOrder: 5 },
  { id: "ai-workspace",   name: "AI Workspace",      description: "Notion, Manus, Gamma", icon: "🏢", sortOrder: 6 },
  { id: "ai-writing",     name: "AI Writing",        description: "Writesonic", icon: "✍️", sortOrder: 7 },
  { id: "bundles",        name: "Bundles & Services",description: "Curated AI packs and implementation services", icon: "📦", sortOrder: 8 },
];

const products = [
  { id: "chatgpt-plus-starter-shared", name: "ChatGPT Plus — Starter Shared", slug: "chatgpt-plus-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 350, officialUsd: 20, tier: "Starter Shared", accessType: "shared", badge: "Best Seller", description: "Budget-friendly shared ChatGPT Plus. GPT-5 series for text, code, vision, search, DALL-E, AI agents.", capabilities: ["text","code","vision","search","image-gen","agents"], deliverySla: "5-30 min", featured: true, whatsappMsg: "Hi, I want ChatGPT Plus Starter Shared (৳350/mo)", status: "Active", sortOrder: 1 },
  { id: "chatgpt-plus-premium-shared", name: "ChatGPT Plus — Premium Shared", slug: "chatgpt-plus-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 950, officialUsd: 20, tier: "Premium Shared", accessType: "shared", badge: "High Stability", description: "Premium shared ChatGPT Plus. 2-3 users max, higher stability. Full GPT-5 multimodal.", capabilities: ["text","code","vision","search","image-gen","agents"], deliverySla: "5-15 min", featured: true, whatsappMsg: "Hi, I want ChatGPT Plus Premium Shared (৳950/mo)", status: "Active", sortOrder: 2 },
  { id: "chatgpt-plus-personal", name: "ChatGPT Plus — Personal", slug: "chatgpt-plus-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 2990, officialUsd: 20, tier: "Personal", accessType: "personal", badge: null, description: "Full personal ChatGPT Plus. GPT-5.4 thinking, DALL-E, deep research, agent mode, Codex, custom GPTs.", capabilities: ["text","code","vision","document","search","image-gen","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want ChatGPT Plus Personal (৳2,990/mo)", status: "Active", sortOrder: 3 },
  { id: "chatgpt-go-personal", name: "ChatGPT Go — Personal", slug: "chatgpt-go-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 1196, officialUsd: 8, tier: "Go", accessType: "personal", badge: null, description: "ChatGPT Go — official $8/mo plan.", capabilities: ["text","code","vision","search","image-gen","agents"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want ChatGPT Go Personal (৳1,196/mo)", status: "Active", sortOrder: 4 },
  { id: "chatgpt-business-starter-shared", name: "ChatGPT Business — Starter Shared", slug: "chatgpt-business-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 699, officialUsd: 25, tier: "Starter Shared", accessType: "shared", badge: "For Teams", description: "Shared ChatGPT Business seat.", capabilities: ["text","code","vision","document","search","image-gen","agents"], deliverySla: "5-30 min", featured: true, whatsappMsg: "Hi, I want ChatGPT Business Starter Shared (৳699/mo)", status: "Active", sortOrder: 5 },
  { id: "chatgpt-business-personal", name: "ChatGPT Business — Personal", slug: "chatgpt-business-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 3990, officialUsd: 30, tier: "Personal", accessType: "personal", badge: null, description: "Dedicated ChatGPT Business seat.", capabilities: ["text","code","vision","document","search","image-gen","agents"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want ChatGPT Business Personal (৳3,990/mo)", status: "Active", sortOrder: 7 },
  { id: "chatgpt-pro-premium-shared", name: "ChatGPT Pro — Premium Shared", slug: "chatgpt-pro-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 4500, officialUsd: 200, tier: "Premium Shared", accessType: "shared", badge: "Best Value Pro", description: "Shared ChatGPT Pro. Unlimited GPT-5.4 Pro, Sora video.", capabilities: ["text","code","vision","document","search","image-gen","video-gen","agents"], deliverySla: "2-12 hours", featured: true, whatsappMsg: "Hi, I want ChatGPT Pro Premium Shared (৳4,500/mo)", status: "Active", sortOrder: 8 },
  { id: "chatgpt-pro-personal", name: "ChatGPT Pro — Personal", slug: "chatgpt-pro-bangladesh", brand: "ChatGPT", brandSlug: "chatgpt-plans-bangladesh", provider: "OpenAI", brandColor: "#10a37f", category: "ai-assistant", price: 29900, officialUsd: 200, tier: "Personal", accessType: "personal", badge: null, description: "Full ChatGPT Pro. Unlimited GPT-5.4 Pro, Sora.", capabilities: ["text","code","vision","document","search","image-gen","video-gen","agents"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want ChatGPT Pro Personal (৳29,900/mo)", status: "Active", sortOrder: 9 },
  { id: "claude-pro-premium-shared", name: "Claude Pro — Premium Shared", slug: "claude-pro-bangladesh", brand: "Claude", brandSlug: "claude-pro-bangladesh", provider: "Anthropic", brandColor: "#d97706", category: "ai-assistant", price: 1495, officialUsd: 20, tier: "Premium Shared", accessType: "shared", badge: "Top Pick", description: "Premium shared Claude Pro. Opus 4.6, Claude Code, MCP integrations.", capabilities: ["text","code","vision","document","agents"], deliverySla: "5-15 min", featured: true, whatsappMsg: "Hi, I want Claude Pro Premium Shared (৳1,495/mo)", status: "Active", sortOrder: 10 },
  { id: "claude-pro-personal", name: "Claude Pro — Personal", slug: "claude-pro-bangladesh", brand: "Claude", brandSlug: "claude-pro-bangladesh", provider: "Anthropic", brandColor: "#d97706", category: "ai-assistant", price: 2990, officialUsd: 20, tier: "Personal", accessType: "personal", badge: null, description: "Full personal Claude Pro. All models incl. Opus 4.6.", capabilities: ["text","code","vision","document","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Claude Pro Personal (৳2,990/mo)", status: "Active", sortOrder: 11 },
  { id: "claude-max-5x", name: "Claude Max 5x — Personal", slug: "claude-pro-bangladesh", brand: "Claude", brandSlug: "claude-pro-bangladesh", provider: "Anthropic", brandColor: "#d97706", category: "ai-assistant", price: 14950, officialUsd: 100, tier: "Max 5x", accessType: "personal", badge: null, description: "Claude Max 5x. 5x Pro limits, 1M token context.", capabilities: ["text","code","vision","document","agents"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want Claude Max 5x (৳14,950/mo)", status: "Active", sortOrder: 12 },
  { id: "claude-team-personal", name: "Claude Team — Personal Seat", slug: "claude-pro-bangladesh", brand: "Claude", brandSlug: "claude-pro-bangladesh", provider: "Anthropic", brandColor: "#d97706", category: "ai-assistant", price: 3990, officialUsd: 30, tier: "Team", accessType: "personal", badge: null, description: "Claude Team seat. All Pro features + admin controls.", capabilities: ["text","code","vision","document","agents"], deliverySla: "2-12 hours", featured: false, whatsappMsg: "Hi, I want Claude Team (৳3,990/seat/mo)", status: "Active", sortOrder: 14 },
  { id: "google-ai-pro-personal", name: "Google AI Pro — Personal", slug: "gemini-advanced-bangladesh", brand: "Google", brandSlug: "gemini-advanced-bangladesh", provider: "Google", brandColor: "#4285f4", category: "ai-assistant", price: 500, officialUsd: 19, tier: "Personal", accessType: "personal", badge: "83% Off", description: "AIPS SPECIAL — Full Google AI Pro on YOUR Gmail. Gemini 3.1 Pro, Deep Research, 2TB storage.", capabilities: ["text","code","vision","document","search","image-gen","video-gen","agents","workspace"], deliverySla: "5-15 min", featured: true, whatsappMsg: "Hi, I want Google AI Pro (৳500/mo)", status: "Active", sortOrder: 15 },
  { id: "supergrok-personal", name: "SuperGrok — Personal", slug: "supergrok-bangladesh", brand: "Grok", brandSlug: "supergrok-bangladesh", provider: "xAI", brandColor: "#000000", category: "ai-assistant", price: 3990, officialUsd: 30, tier: "Standard", accessType: "personal", badge: null, description: "Full SuperGrok. Grok 4.1 unlimited, DeepSearch, HD images.", capabilities: ["text","code","vision","search","image-gen","video-gen","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want SuperGrok (৳3,990/mo)", status: "Active", sortOrder: 17 },
  { id: "perplexity-pro-shared", name: "Perplexity Pro — Shared", slug: "perplexity-pro-bangladesh", brand: "Perplexity", brandSlug: "perplexity-pro-bangladesh", provider: "Perplexity", brandColor: "#20b2aa", category: "ai-assistant", price: 350, officialUsd: 20, tier: "Shared", accessType: "shared", badge: null, description: "Shared Perplexity Pro. 300+ Pro searches/day.", capabilities: ["text","search","document"], deliverySla: "5-15 min", featured: true, whatsappMsg: "Hi, I want Perplexity Pro Shared (৳350/mo)", status: "Active", sortOrder: 18 },
  { id: "midjourney-std-shared", name: "Midjourney Standard — Shared", slug: "midjourney-bangladesh", brand: "Midjourney", brandSlug: "midjourney-bangladesh", provider: "Midjourney", brandColor: "#1a1a2e", category: "ai-image", price: 1199, officialUsd: 30, tier: "Shared", accessType: "shared", badge: "Best Seller", description: "Shared Midjourney Standard. 15hr fast GPU, unlimited relax mode.", capabilities: ["image-gen","video-gen"], deliverySla: "5-30 min", featured: true, whatsappMsg: "Hi, I want Midjourney Standard Shared (৳1,199/mo)", status: "Active", sortOrder: 21 },
  { id: "midjourney-std-personal", name: "Midjourney Standard — Personal", slug: "midjourney-bangladesh", brand: "Midjourney", brandSlug: "midjourney-bangladesh", provider: "Midjourney", brandColor: "#1a1a2e", category: "ai-image", price: 3990, officialUsd: 30, tier: "Personal", accessType: "personal", badge: null, description: "Full personal Midjourney Standard.", capabilities: ["image-gen","video-gen"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want Midjourney Standard Personal (৳3,990/mo)", status: "Active", sortOrder: 23 },
  { id: "midjourney-pro-personal", name: "Midjourney Pro — Personal", slug: "midjourney-bangladesh", brand: "Midjourney", brandSlug: "midjourney-bangladesh", provider: "Midjourney", brandColor: "#1a1a2e", category: "ai-image", price: 8970, officialUsd: 60, tier: "Pro", accessType: "personal", badge: null, description: "Full Midjourney Pro. 30hr fast GPU, stealth mode, HD video.", capabilities: ["image-gen","image-edit","video-gen"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want Midjourney Pro Personal (৳8,970/mo)", status: "Active", sortOrder: 25 },
  { id: "runway-std-personal", name: "Runway Standard — Personal", slug: "runway-bangladesh", brand: "Runway", brandSlug: "runway-bangladesh", provider: "Runway", brandColor: "#111827", category: "ai-video", price: 1794, officialUsd: 12, tier: "Standard", accessType: "personal", badge: "Best Seller", description: "Runway Standard. 625 credits/mo, Gen-4 video.", capabilities: ["video-gen","video-edit","image-gen"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Runway Standard (৳1,794/mo)", status: "Active", sortOrder: 30 },
  { id: "heygen-creator-shared", name: "HeyGen Creator — Shared", slug: "heygen-bangladesh", brand: "HeyGen", brandSlug: "heygen-bangladesh", provider: "HeyGen", brandColor: "#6366f1", category: "ai-video", price: 1499, officialUsd: 29, tier: "Shared", accessType: "shared", badge: null, description: "Shared HeyGen Creator. AI avatar videos, 700+ avatars, voice cloning.", capabilities: ["video-gen","voice"], deliverySla: "5-30 min", featured: false, whatsappMsg: "Hi, I want HeyGen Creator Shared (৳1,499/mo)", status: "Active", sortOrder: 33 },
  { id: "elevenlabs-starter-personal", name: "ElevenLabs Starter — Personal", slug: "elevenlabs-bangladesh", brand: "ElevenLabs", brandSlug: "elevenlabs-bangladesh", provider: "ElevenLabs", brandColor: "#111827", category: "ai-voice-music", price: 748, officialUsd: 5, tier: "Starter", accessType: "personal", badge: null, description: "ElevenLabs Starter. 30K characters TTS/mo.", capabilities: ["voice"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want ElevenLabs Starter (৳748/mo)", status: "Active", sortOrder: 34 },
  { id: "suno-pro-personal", name: "Suno AI Pro — Personal", slug: "suno-ai-bangladesh", brand: "Suno", brandSlug: "suno-ai-bangladesh", provider: "Suno", brandColor: "#7c3aed", category: "ai-voice-music", price: 1495, officialUsd: 10, tier: "Pro", accessType: "personal", badge: "Best Seller", description: "Suno AI Pro. 2500 credits/mo (~500 songs), v5.5 model.", capabilities: ["music"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Suno AI Pro (৳1,495/mo)", status: "Active", sortOrder: 37 },
  { id: "udio-pro-shared", name: "Udio Pro — Shared", slug: "udio-bangladesh", brand: "Udio", brandSlug: "udio-bangladesh", provider: "Udio", brandColor: "#ec4899", category: "ai-voice-music", price: 499, officialUsd: 10, tier: "Shared", accessType: "shared", badge: null, description: "Shared Udio Pro. AI music creation.", capabilities: ["music"], deliverySla: "5-30 min", featured: false, whatsappMsg: "Hi, I want Udio Pro Shared (৳499/mo)", status: "Active", sortOrder: 39 },
  { id: "github-copilot-pro-personal", name: "GitHub Copilot Pro — Personal", slug: "github-copilot-bangladesh", brand: "GitHub", brandSlug: "github-copilot-bangladesh", provider: "GitHub", brandColor: "#6e40c9", category: "ai-code", price: 1495, officialUsd: 10, tier: "Pro", accessType: "personal", badge: "Best Seller", description: "GitHub Copilot Pro. Unlimited code completions.", capabilities: ["code"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want GitHub Copilot Pro (৳1,495/mo)", status: "Active", sortOrder: 40 },
  { id: "cursor-pro-personal", name: "Cursor Pro — Personal", slug: "cursor-bangladesh", brand: "Cursor", brandSlug: "cursor-bangladesh", provider: "Cursor", brandColor: "#111827", category: "ai-code", price: 2990, officialUsd: 20, tier: "Pro", accessType: "personal", badge: "Best Seller", description: "Cursor Pro AI code editor.", capabilities: ["code","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Cursor Pro (৳2,990/mo)", status: "Active", sortOrder: 42 },
  { id: "replit-core-personal", name: "Replit Core — Personal", slug: "replit-bangladesh", brand: "Replit", brandSlug: "replit-bangladesh", provider: "Replit", brandColor: "#f26207", category: "ai-code", price: 500, officialUsd: 20, tier: "Core", accessType: "personal", badge: "Special Deal", description: "AIPS SPECIAL — Replit Core at ৳500.", capabilities: ["code","agents"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want Replit Core (৳500/mo)", status: "Active", sortOrder: 45 },
  { id: "notion-business-monthly", name: "Notion Business — Monthly", slug: "notion-business-bangladesh", brand: "Notion", brandSlug: "notion-business-bangladesh", provider: "Notion", brandColor: "#111827", category: "ai-workspace", price: 800, officialUsd: 20, tier: "Monthly", accessType: "personal", badge: "73% Off", description: "Official Notion Business Plan. Notion AI included.", capabilities: ["workspace","text","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Notion Business Monthly (৳800/mo)", status: "Active", sortOrder: 46 },
  { id: "notion-business-6m", name: "Notion Business — 6 Month Plan", slug: "notion-business-bangladesh", brand: "Notion", brandSlug: "notion-business-bangladesh", provider: "Notion", brandColor: "#111827", category: "ai-workspace", price: 4800, officialUsd: 120, tier: "6-Month", accessType: "personal", badge: null, description: "Notion Business 6-month plan.", capabilities: ["workspace","text","agents"], deliverySla: "2-4 hours", featured: true, whatsappMsg: "Hi, I want Notion Business 6-Month (৳4,800)", status: "Active", sortOrder: 47 },
  { id: "student-essentials", name: "Student Essentials Package", slug: "student-package-bangladesh", brand: "AIPS", brandSlug: "bundles", provider: "AIPS", brandColor: "#f4b942", category: "bundles", price: 449, officialUsd: null, tier: "Essentials", accessType: "bundle", badge: null, description: "AI bundle for students.", capabilities: ["text","code"], deliverySla: "5-30 min", featured: false, whatsappMsg: "Hi, I want Student Essentials Package (৳449)", status: "Active", sortOrder: 52 },
  { id: "freelancer-bundle", name: "Freelancer Bundle", slug: "freelancer-bundle-bangladesh", brand: "AIPS", brandSlug: "bundles", provider: "AIPS", brandColor: "#f4b942", category: "bundles", price: 3999, officialUsd: null, tier: "Bundle", accessType: "bundle", badge: null, description: "AI toolkit for freelancers.", capabilities: ["text","code","image-gen"], deliverySla: "2-4 hours", featured: false, whatsappMsg: "Hi, I want Freelancer Bundle (৳3,999)", status: "Active", sortOrder: 54 },
  { id: "business-package", name: "Business Package", slug: "business-package-bangladesh", brand: "AIPS", brandSlug: "bundles", provider: "AIPS", brandColor: "#f4b942", category: "bundles", price: 15000, officialUsd: null, tier: "Business", accessType: "bundle", badge: null, description: "Full AI stack for businesses.", capabilities: ["text","code","image-gen","workspace"], deliverySla: "2-12 hours", featured: false, whatsappMsg: "Hi, I want Business Package (৳15,000)", status: "Active", sortOrder: 55 },
];

async function seed() {
  console.log("🌱 Seeding AIPS database...");
  for (const cat of categories) {
    await db.insert(categoriesTable).values(cat).onConflictDoNothing();
  }
  console.log(`✅ ${categories.length} categories inserted`);
  for (const product of products) {
    await db.insert(productsTable).values(product).onConflictDoNothing();
  }
  console.log(`✅ ${products.length} products inserted`);
  console.log("🎉 Seed complete!");
}

seed().catch((err) => { console.error("❌ Seed failed:", err); process.exit(1); });
